# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATA_TEST)/property

TESTPROD_HOST += testProperty
testProperty_SRCS += testProperty.cpp
testHarness_SRCS += testProperty.cpp
TESTS += testProperty
