TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testProperty
testProperty_SRCS += testProperty.cpp
testProperty_LIBS += pvData  Com


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

