# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATA_TEST)/pv

TESTPROD_HOST += testBitSetUtil
testBitSetUtil_SRCS += testBitSetUtil.cpp
testHarness_SRCS += testBitSetUtil.cpp
TESTS += testBitSetUtil

TESTPROD_HOST += testIntrospect
testIntrospect_SRCS += testIntrospect.cpp
testHarness_SRCS += testIntrospect.cpp
TESTS += testIntrospect

TESTPROD_HOST += testPVType
testPVType_SRCS += testPVType.cpp
testHarness_SRCS += testPVType.cpp
TESTS += testPVType

TESTPROD_HOST += testStandardField
testStandardField_SRCS += testStandardField.cpp
testHarness_SRCS += testStandardField.cpp
TESTS += testStandardField

TESTPROD_HOST += testStandardPVField
testStandardPVField_SRCS += testStandardPVField.cpp
testHarness_SRCS += testStandardPVField.cpp
TESTS += testStandardPVField

TESTPROD_HOST += testPVData
testPVData_SRCS += testPVData.cpp
testHarness_SRCS += testPVData.cpp
TESTS += testPVData

TESTPROD_HOST += testPVUnion
testPVUnion_SRCS += testPVUnion.cpp
testHarness_SRCS += testPVUnion.cpp
TESTS += testPVUnion

TESTPROD_HOST += testConvert
testConvert_SRCS += testConvert.cpp
testHarness_SRCS += testConvert.cpp
TESTS += testConvert

TESTPROD_HOST += testPVScalarArray
testPVScalarArray_SRCS += testPVScalarArray.cpp
testHarness_SRCS += testPVScalarArray.cpp
TESTS += testPVScalarArray

TESTPROD_HOST += testPVStructureArray
testPVStructureArray_SRCS += testPVStructureArray.cpp
testHarness_SRCS += testPVStructureArray.cpp
TESTS += testPVStructureArray

TESTPROD_HOST += testOperators
testOperators_SRCS += testOperators.cpp
testHarness_SRCS += testOperators.cpp
TESTS += testOperators

TESTPROD_HOST += testFieldBuilder
testFieldBuilder_SRCS += testFieldBuilder.cpp
testHarness_SRCS += testFieldBuilder.cpp
TESTS += testFieldBuilder

TESTPROD_HOST += testValueBuilder
testValueBuilder_SRCS += testValueBuilder.cpp
TESTS += testValueBuilder

TESTPROD_Linux += performstruct
performstruct_SRCS += performstruct.cpp
performstruct_SYS_LIBS_Linux += rt
