TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testMonitor
testMonitor_SRCS += testMonitor.cpp
testMonitor_LIBS += pvData  Com


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

