TOP=../..

include $(TOP)/configure/CONFIG

INC += factory.h
INC += AbstractPVField.h
INC += AbstractPVScalar.h
INC += AbstractPVArray.h
INC += AbstractPVScalarArray.h
INC += BasePVStructure.h
INC += BasePVBoolean.h
INC += BasePVByte.h
INC += BasePVShort.h
INC += BasePVInt.h
INC += BasePVLong.h
INC += BasePVFloat.h
INC += BasePVDouble.h
INC += BasePVString.h
INC += BasePVBooleanArray.h
INC += BasePVByteArray.h
INC += BasePVShortArray.h
INC += BasePVIntArray.h
INC += BasePVLongArray.h
INC += BasePVFloatArray.h
INC += BasePVDoubleArray.h
INC += BasePVString.h
INC += BasePVStructure.h
INC += BasePVStructureArray.h
LIBSRCS += TypeFunc.cpp
LIBSRCS += PVAuxInfoImpl.cpp
LIBSRCS += FieldCreateFactory.cpp
LIBSRCS += PVDataCreateFactory.cpp
LIBSRCS += Convert.cpp
LIBSRCS += StandardField.cpp
LIBSRCS += StandardPVField.cpp

LIBRARY=pvFactory

pvFactory_LIBS += Com

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

