TOP=../..

include $(TOP)/configure/CONFIG

LIBSRCS += FieldCreateFactory.cpp

LIBRARY=pvFactory

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

