TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += mb_test
mb_test_CXXFLAGS += -DPV_MB
mb_test_SRCS += mb_test.cpp
mb_test_LIBS += pvData Com

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

