# Makefile for the examples
# make sure they compile

TOP = ..
include $(TOP)/configure/CONFIG

PROD_LIBS += pvData Com

TESTPROD_HOST += unittest
unittest_SRCS += unittest.cpp

include $(TOP)/configure/RULES


