TOP=../..

include $(TOP)/configure/CONFIG

INC += enumerated.h
INC += pvTimeStamp.h

#LIBSRCS += enumerated.cpp 
#LIBSRCS += pvTimeStamp.cpp
#enumerated_LIBS += pvFactory pvMisc Com

#LIBRARY=pvProperty


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

