TOP=../..

include $(TOP)/configure/CONFIG

INC += enumerated.h

LIBSRCS += enumerated.cpp
enumerated_LIBS += pvFactory pvMisc Com

LIBRARY=pvProperty


include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

