# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATA_SRC)/copy

INC += pv/createRequest.h
INC += pv/pvCopy.h
INC += pv/pvPlugin.h
INC += pv/pvArrayPlugin.h
INC += pv/pvDeadbandPlugin.h
INC += pv/pvTimestampPlugin.h


LIBSRCS += createRequest.cpp
LIBSRCS += pvCopy.cpp
LIBSRCS += pvPlugin.cpp
LIBSRCS += pvArrayPlugin.cpp
LIBSRCS += pvDeadbandPlugin.cpp
LIBSRCS += pvTimestampPlugin.cpp
