# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATA_SRC)/copy

INC += pv/createRequest.h
INC += pv/pvCopy.h

LIBSRCS += createRequest.cpp
LIBSRCS += requestmask.cpp
LIBSRCS += pvCopy.cpp
