TOP = ..
include $(TOP)/configure/CONFIG
DIRS += misc
DIRS += pv
DIRS += property
DIRS += copy

# TODO combined test vxTestHarness
#PROD_vxWorks = vxTestHarness
#vxTestHarness_SRCS += pvDataAllTests
#vxTestHarness_OBJS += misc/
#TESTSPEC_vxWorks = vxTestHarness.$(MUNCH_SUFFIX); pvDataAllTests

include $(TOP)/configure/RULES_DIRS


