TOP=../..

include $(TOP)/configure/CONFIG

PROD_HOST += testIntrospect
testIntrospect_SRCS += testIntrospect.cpp
testIntrospect_LIBS += pvFactory

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

