# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATA_SRC)/property

INC += pv/alarm.h
INC += pv/pvAlarm.h
INC += pv/control.h
INC += pv/pvControl.h
INC += pv/display.h
INC += pv/pvDisplay.h
INC += pv/pvEnumerated.h
INC += pv/timeStamp.h
INC += pv/pvTimeStamp.h

LIBSRCS += alarm.cpp
LIBSRCS += pvAlarm.cpp
LIBSRCS += pvControl.cpp
LIBSRCS += pvDisplay.cpp
LIBSRCS += pvEnumerated.cpp
LIBSRCS += timeStamp.cpp
LIBSRCS += pvTimeStamp.cpp

