TOP=../..

include $(TOP)/configure/CONFIG

INC += pvIntrospect.h
INC += pvData.h
INC += convert.h
INC += standardField.h

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

