# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATA_SRC)/pv

INC += pvType.h
INC += pvIntrospect.h
INC += pvData.h
INC += convert.h
INC += standardField.h
INC += standardPVField.h
INC += pvSubArrayCopy.h

