# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATA_SRC)/pv

INC += pv/pvType.h
INC += pv/pvIntrospect.h
INC += pv/valueBuilder.h
INC += pv/pvData.h
INC += pv/convert.h
INC += pv/standardField.h
INC += pv/standardPVField.h
INC += pv/pvSubArrayCopy.h
INC += pv/typemap.h
INC += pv/pvdVersion.h
INC += pv/pvdVersionNum.h

LIBSRCS += pvdVersion.cpp
LIBSRCS += valueBuilder.cpp
