# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVDATA_TEST)/copy

TESTPROD_HOST += testCreateRequest
testCreateRequest_SRCS = testCreateRequest.cpp
testHarness_SRCS += testCreateRequest.cpp
TESTS += testCreateRequest
